export function Person() {}
export function Organization() {}
export function name() {}
export function birthday() {}
export function gender() {}
export function weblog() {}
export function mbox() {}
export function homepage() {}
export function phone() {}
